### ISSUE TITLE
[ERROR] 'EsctlTransport' object has no attribute 'meta_header'

### ISSUE THREAD

**Issue by murarisumit** [jeromepin/esctl#8]
Getting this error after setting up for first time.: `[ERROR] 'EsctlTransport' object has no attribute 'meta_header'`. 

Python version
```
 $ > python --version
Python 3.9.1
```

ESCTL
```
 $ > pip freeze | grep esctl
esctl==1.7.0
```

Config
```
clusters:
  localhost:
    servers:
    - http://localhost:9200
  cluster1:
    servers:
    - https://foo.bar.com:443
contexts:
  ctx1:
    cluster: cluster1
    user: elastic
  localhost:
    cluster: localhost
default-context: ctx1
settings: {}
users:
  elastic:
    password: pass
    username: uname
```

Let me know if some details are required for it.
