### ISSUE TITLE
Password prompt

### ISSUE THREAD

**Issue by mikelitka** [jeromepin/esctl#9]
Thanks for your hard work here. Have you considered adding a password prompt so the plaintext passwords don't need to be stored on the filesystem?

**Comment by jeromepin** [comment]
Sorry for my late answer, I didn't had any notification 😥 

I never thought about a prompt. But in 1.8 I added the ability to call a shell command to retrieve the password. You can see an example [in the README](https://github.com/jeromepin/esctl#how-to-use) :

```yaml
users:
  john-doe:
    username: john
    external_password:
      command:
        run: kubectl --context=bar --namespace=baz get secrets -o json my-secret | jq -r '.data.password|@base64d'
```

I think it covers enough use-cases for anyone to be happy.
